name: Telenor Quiz Daily Update

on:
  workflow_dispatch:

  schedule:
    # Pakistan time:
    # 5:00 PM  = UTC 12:00
    # 6:00 PM  = UTC 13:00
    # 7:00 PM  = UTC 14:00
    # 8:00 PM  = UTC 15:00
    # 9:00 PM  = UTC 16:00
    # 10:00 PM = UTC 17:00
    # 11:00 PM = UTC 18:00
    - cron: "0 12-18 * * *"

    # 12:05 AM Pakistan time
    - cron: "5 19 * * *"

permissions:
  contents: write

jobs:
  update-quiz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch and Verify Today's Quiz
        run: node poster.js

      - name: Commit Updated Quiz
        run: |
          git config user.name "Telenor Quiz Bot"
          git config user.email "bot@telenorquizpk.com"

          git add quiz.json

          if git diff --cached --quiet; then
            echo "No new quiz update."
          else
            git commit -m "Update verified daily Telenor quiz"
            git push
          fi
