name: Telenor Quiz Daily Update

on:
  workflow_dispatch:

  schedule:
    # Pakistan 5:00 AM = UTC 00:00
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-quiz:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Quiz Poster
        run: node poster.js

      - name: Commit Updated Quiz
        run: |
          git config user.name "Telenor Quiz Bot"
          git config user.email "bot@telenorquizpk.com"

          git add quiz.json

          git diff --cached --quiet || git commit -m "Update daily Telenor quiz"

          git push
